#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/access-service/.env"
ROOT_ENV="$REPO_ROOT/.env"
REDIRECT_URI="http://127.0.0.1:8787/v1/auth/google/callback"

TOTAL_STAGES=6
TOTAL_MINUTES=15

banner "Access Service — Google OAuth Web client (#14)"

# ── 1. GCP project ────────────────────────────────────────────────────────
stage "Pick GCP project" 2
say "Use the same GCP project that owns your restricted Maps browser key"
say "(or a dedicated auth project — note which, for the ops README)."
open_url "https://console.cloud.google.com/home/dashboard"
step "Confirm the project picker (top bar) shows the right project."
step "If you need a new project: open the picker → New Project → create it, then select it."
pause "Project selected? Press Enter."

# ── 2. OAuth consent screen ───────────────────────────────────────────────
stage "OAuth consent screen" 4
say "Register the app Google shows on the consent page (required before Clients)."
open_url "https://console.cloud.google.com/auth/overview"
step "If prompted to Get started / Configure consent: continue."
step "App name: e.g. Strava Streets (Access)."
step "User support email + developer contact: your Google account email."
step "Audience: External (Personal / Store testing) or Internal (Workspace-only)."
step "Scopes: keep defaults or ensure openid is available — Access Service only requests openid."
step "If Audience is External and status is Testing: add yourself under Test users."
note "Branding / Audience tabs may be labeled under 'Google Auth platform'."
pause "Consent screen saved? Press Enter."

# ── 3. Web application client + redirect URI ──────────────────────────────
stage "Create OAuth Web client" 4
say "Create a Web application client. Redirect must match Access Service exactly."
open_url "https://console.cloud.google.com/auth/clients"
step "Click Create client (or Create credentials → OAuth client ID)."
step "Application type: Web application."
step "Name: e.g. Access Service (local)."
step "Under Authorized redirect URIs → Add URI, paste exactly:"
note "  $REDIRECT_URI"
step "Leave Authorized JavaScript origins empty for this server flow."
step "Click Create."
step "Copy Client ID and Client secret from the dialog (or the client detail page)."
warn "Client secret is server-only — never put it in the extension or Store build."
ask GOOGLE_OAUTH_CLIENT_ID "Paste Client ID:"
ask_secret GOOGLE_OAUTH_CLIENT_SECRET "Paste Client secret:"
if [[ -z "$GOOGLE_OAUTH_CLIENT_ID" || -z "$GOOGLE_OAUTH_CLIENT_SECRET" ]]; then
  warn "Both Client ID and secret are required."
  exit 1
fi

# ── 4. Write Access Service env ───────────────────────────────────────────
stage "Write access-service/.env" 2
say "Persisting OAuth env for local npm start (gitignored)."
write_env GOOGLE_OAUTH_CLIENT_ID "$GOOGLE_OAUTH_CLIENT_ID"
write_env GOOGLE_OAUTH_CLIENT_SECRET "$GOOGLE_OAUTH_CLIENT_SECRET"
write_env PUBLIC_ORIGIN "http://127.0.0.1:8787"

GOOGLE_OAUTH_STATE_SECRET=""
current=$(_existing GOOGLE_OAUTH_STATE_SECRET || true)
if [[ -n "$current" ]]; then
  if confirm "Keep existing GOOGLE_OAUTH_STATE_SECRET?"; then
    GOOGLE_OAUTH_STATE_SECRET="$current"
  fi
fi
if [[ -z "$GOOGLE_OAUTH_STATE_SECRET" ]]; then
  GOOGLE_OAUTH_STATE_SECRET="$(openssl rand -hex 32)"
  note "Generated a new GOOGLE_OAUTH_STATE_SECRET (HMAC for CSRF state)."
fi
write_env GOOGLE_OAUTH_STATE_SECRET "$GOOGLE_OAUTH_STATE_SECRET"

# ── 5. Maps browser key for Mint ──────────────────────────────────────────
stage "Maps browser key (Mint)" 2
say "Access Service mints this restricted Maps browser key to the extension."
MAPS_FROM_ROOT=""
if [[ -f "$ROOT_ENV" ]]; then
  MAPS_FROM_ROOT=$(grep -E '^GOOGLE_MAPS_API_KEY=' "$ROOT_ENV" | tail -n1 | cut -d= -f2- || true)
fi
if [[ -n "$MAPS_FROM_ROOT" ]]; then
  say "Found GOOGLE_MAPS_API_KEY in repo-root .env (Dev Key Override)."
  if confirm "Reuse that value as MAPS_BROWSER_KEY in access-service/.env?"; then
    write_env MAPS_BROWSER_KEY "$MAPS_FROM_ROOT"
  fi
fi
if [[ -z "$(_existing MAPS_BROWSER_KEY || true)" ]]; then
  open_url "https://console.cloud.google.com/apis/credentials"
  step "Open your restricted Maps browser key (or create one) and copy it."
  step "Referrer allowlist should include https://www.strava.com/maps/*"
  ask_secret MAPS_BROWSER_KEY "Paste MAPS_BROWSER_KEY (or Enter to skip for now):"
  if [[ -n "$MAPS_BROWSER_KEY" ]]; then
    write_env MAPS_BROWSER_KEY "$MAPS_BROWSER_KEY"
  else
    SKIPPED+=("MAPS_BROWSER_KEY — set later for real Mint; OAuth still works without it")
    note "Skipped MAPS_BROWSER_KEY — login smoke still works; Mint needs it."
  fi
fi

# ── 6. Smoke check ────────────────────────────────────────────────────────
stage "Smoke check" 1
say "Verify the production Google Auth Adapter starts and the redirect URI matches."
step "In another terminal:"
note "  cd access-service && npm start"
step "You should see: OAuth Adapter: production Google OAuth"
step "Open the start URL (opens Google consent, then bounces back):"
note "  $REDIRECT_URI → via http://127.0.0.1:8787/v1/auth/google/start"
open_url "http://127.0.0.1:8787/v1/auth/google/start"
step "After Google: expect JSON {\"ok\":true} and a Set-Cookie access_session."
warn "If redirect_uri_mismatch: re-check the Web client redirect URI is exactly:"
note "  $REDIRECT_URI"
pause "Smoke done (or skipped until npm start)? Press Enter."

finish
say "Next: keep access-service/.env private; never commit Client secret."
say "Deployed hosts later: add https://<host>/v1/auth/google/callback in Console + PUBLIC_ORIGIN."
